apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:
  name: employee-app

spec:
  selector:
    matchLabels:
      app: employee-app

  endpoints:
    - port: http
      interval: 30s
      path: /metrics